@startuml
actor       Admin                       as admin
boundary    adminUI                     as adminUI
control     groupController             as groupController
control     jbicController              as jbicController
collections groupService                as groupService
collections jbicService                 as jbicService
collections licenseService              as licenseService
collections arloAuthMiddleware          as arloAuthMiddleware
collections arloAuthService             as arloAuthService
collections arloResourcesService        as arloResourcesService
entity      JBICOrganizationsRepository as JBICOrganizationsRepository
entity      GroupRepository             as GroupRepository
entity      licenseRepository           as licenseRepository
entity      groupMemberRepository       as groupMemberRepository
database    DB                          as DB
database    Cache                       as Cache
participant ARLO                        as ARLO

activate adminUI #lightgrey
admin -> adminUI : [Web page] /group/<ID>
admin -> adminUI : Add member to sub group

group update group and update ARLO organization
adminUI -> groupController : [HTTPS POST] /group/<ID>/member

activate groupController
groupController -> groupService : CALL addMemberIntoSubGroup(payload)
activate groupService
groupService -> GroupRepository : CALL getByID(<ID>)
activate GroupRepository
activate DB
GroupRepository -> DB : getOne() query
DB --> GroupRepository : GroupEntity
GroupRepository --> groupService : GroupEntity


groupService -> GroupRepository : CALL update (GroupEntity, payload)

GroupRepository -> DB : update() query

alt#Gold #ADE792 Success
DB --> GroupRepository : GroupEntity
GroupRepository --> groupService : GroupEntity
else #pink Failure: SQL error
DB --> GroupRepository : [Error] SQL Error
GroupRepository --> groupService: [Error] SQL Error
deactivate DB
groupService -->groupController: [Error] Unprocessable Entity, Error in updating group
groupController --> adminUI : [Error: 422] Unprocessable Entity, Error in updating group
adminUI -> admin : show dialog box with error
end
deactivate GroupRepository

groupService -> jbicService : CALL getLicenseBySubGroup(subGroupDetail: GroupEntity)
jbicService --> licenseService: CALL getLicenseBySubGroup(subGroupDetail: GroupEntity)
activate jbicService #lightblue

group ARLO: Add member
licenseService --> licenseRepository: CALL getLicenseBySubGroup(subGroupDetail: GroupEntity)
licenseRepository --> DB: getOne() query
DB --> licenseRepository: LicenseEntity
licenseRepository --> licenseService: LicenseEntity
licenseService --> groupService: LicenseEntity
groupService --> groupService: CALL validateSeatCount(subGroupDetail: GroupEntity, licenseDetail: LicenseEntity, payload)

groupService --> arloAuthMiddleware: Check access_token
activate arloAuthMiddleware #yellow
arloAuthMiddleware --> arloAuthService: CALL checkAccessTokenValidity()
activate arloAuthService #red
activate Cache #purple
arloAuthService --> Cache: check for access token **existence** or **expiry** in **jaas_jbic_arlo_oauth2_tokens**
Cache --> arloAuthService: token AND expiry

group No access token found
arloAuthService --> ARLO: GET /oauth/connect/authorize?client_id=ENV_VARIABLE
alt#Gold #ADE792 Success
activate ARLO #FFD100
ARLO --> arloAuthService: GET ENV.ARLO_CALLBACK/oauth/arlo/callback?code=authorisation_code
arloAuthService --> ARLO: POST /ENV.PLATFORM_NAME/oauth/connect/token
ARLO --> arloAuthService: JSON Object (JWT)
arloAuthService --> Cache: **Store** access_token, refresh_token, expires_in
else #pink Failure
ARLO --> arloAuthService: [Error: 401] Access Denied
arloAuthService --> arloAuthMiddleware: [Error: 401] Access Denied
arloAuthMiddleware --> groupService: [Error: 401] Access Denied

activate jbicController #lightgreen
groupService --> groupController: [Error: 500] Error in establishing connection with ARLO
groupController --> adminUI: [Error: 500] Error in establishing connection with ARLO
deactivate jbicController
adminUI -> admin : show dialog box with error
end
end
group Access token found
group Access token expired
activate arloAuthService #red
arloAuthService --> ARLO: /ENV.PLATFORM_NAME/oauth/connect/accesstokenvalidation
group Token invalid
arloAuthService --> ARLO: POST /ENV.PLATFORM_NAME/oauth/connect/token
ARLO --[#green]> arloAuthService: JSON Object (JWT)
arloAuthService --> Cache: **Update** access_token, refresh_token, expires_in
deactivate Cache
end
end
arloAuthService --[#green]> arloAuthService: access_token not expired
arloAuthService --[#green]> arloAuthMiddleware: access_token
deactivate arloAuthMiddleware
deactivate arloAuthService #red
arloAuthMiddleware --[#green]> groupService: access_token
end

alt#Gold #ADE792 Success
groupService --> arloResourcesService: CALL addMemberIntoArloCourse(memberDetail : GroupMemberEntity, courseId = groupDetail["courseId"])
else #pink Seat count exceeded
groupService --> groupController: [validationError] member count exceeds license count]
groupController --> adminUI: [Error: 400] Bad Request, member count exceeds license count, could not add member
adminUI --> admin: dialog with error message "member count exceeds license count, could not add member"
end

arloResourcesService --> ARLO: POST <OrganizationUrl>/auth/resources/registrations/<ID>

activate arloResourcesService #teal

alt#Gold #ADE792 Success
ARLO --> arloResourcesService : [Ok: 200] Success
arloResourcesService --> jbicService : [Ok: 200] Success
jbicService --> groupService : Success
deactivate jbicService
groupService --> groupController : Success
deactivate groupService
groupController --> adminUI: [Ok: 200] Success
adminUI -> admin : redirect to [web page] /group/<ID>
else #pink Failure

ARLO --> arloResourcesService: [Error: 401] Unauthorized
ARLO --> arloResourcesService: [Error: 502] Bad gateway
ARLO --> arloResourcesService: [Error: 500] Error in adding member
deactivate ARLO

activate jbicService #lightblue
arloResourcesService --> jbicService: [Error: 401] Unauthorized
arloResourcesService --> jbicService: [Error: 502] Bad gateway
arloResourcesService --> jbicService: [Error: 500] Error in adding member
deactivate jbicService
activate groupService
deactivate arloResourcesService
jbicService --> groupService: [Error] Error in adding member
activate GroupRepository
groupService -> GroupRepository: [Error] CALL rollbackMember(memberDetail: groupMemberEntity)
activate DB
GroupRepository -> DB : rollback GroupMemberEntity
DB --> GroupRepository : rollback success
GroupRepository -->groupService : rollback success
deactivate DB
deactivate groupService
deactivate GroupRepository
groupService --> groupController : [Error] Error in adding member in ARLO
groupController --> adminUI : [Error: 503] Service not available, Error in adding member in ARLO
adminUI -> admin : show dialog box with error
end
end
@enduml
