@startuml
actor       Admin             as admin
boundary    adminUI           as adminUI
control     groupController   as groupController
control     jbicController    as jbicController
collections groupService      as groupService
collections jbicService      as jbicService
collections arloAuthMiddleware as arloAuthMiddleware
collections arloAuthService  as arloAuthService
collections arloResourcesService as arloResourcesService
entity      GroupRepository       as GroupRepository
database    DB                as DB
database    Cache                as Cache
participant ARLO              as ARLO

admin -> adminUI: [Web page] /group/create
admin -> adminUI: [Web view] Select **JBIC** as group type

group Fetch placeholder organizations
activate adminUI #lightgrey
adminUI -> jbicController: [HTTPS GET] /jbic/fetch-arlo-placeholder-organizations
activate jbicController #lightgreen
jbicController -> jbicService: CALL fetchAllOrganizations()

activate jbicService #lightblue
group ARLO Auth Middleware: Authenticate call
jbicService -> arloAuthMiddleware

activate arloAuthMiddleware #yellow
arloAuthMiddleware --> arloAuthService: CALL checkAccessTokenValidity()
activate arloAuthService #red
activate Cache #magenta
arloAuthService --> Cache: check for access token **existence** or **expiry** in **jaas_jbic_arlo_oauth2_tokens**

Cache --> arloAuthService: token AND expiry

group No access token found
arloAuthService --> ARLO: GET /oauth/connect/authorize?client_id=ENV_VARIABLE
alt#Gold #ADE792 Success
activate ARLO #FFD100
ARLO --> arloAuthService: GET ENV.ARLO_CALLBACK/oauth/arlo/callback?code=authorisation_code
arloAuthService --> ARLO: POST /ENV.PLATFORM_NAME/oauth/connect/token
ARLO --> arloAuthService: JSON Object (JWT)
arloAuthService --> Cache: **Store** access_token, refresh_token, expires_in

else #pink Failure
ARLO --> arloAuthService: [Error: 401] Access Denied
arloAuthService --> arloAuthMiddleware: [Error: 401] Access Denied
arloAuthMiddleware --> jbicService: [Error: 401] Access Denied
jbicService --> jbicController: [Error: 500] Error in establishing connection with ARLO
jbicController --> adminUI: [Error: 500] Error in establishing connection with ARLO
adminUI -> admin : show dialog box with error
deactivate adminUI
end
end

group Access token found
group Access token expired
arloAuthService --> ARLO: /ENV.PLATFORM_NAME/oauth/connect/accesstokenvalidation
group Token invalid
arloAuthService --> ARLO: POST /ENV.PLATFORM_NAME/oauth/connect/token
ARLO --[#green]> arloAuthService: JSON Object (JWT)
arloAuthService --> Cache: **Update** access_token, refresh_token, expires_in

end
end
arloAuthService --[#green]> arloAuthService: access_token not expired
arloAuthService --[#green]> arloAuthMiddleware: access_token
arloAuthMiddleware --[#green]> jbicService: access_token
deactivate arloAuthService
end

deactivate arloAuthMiddleware
jbicService -> arloResourcesService: getOrganisations()
activate arloResourcesService #teal
arloResourcesService --> ARLO: CALL /api/<DATE>/auth/resources/organisations/
alt#Gold #ADE792 Success
ARLO -> arloResourcesService : [ok: 200] arloOrganizations: Organizations JSON Array
arloResourcesService -> jbicService : [ok: 200] arloOrganizations: Organizations JSON Array
jbicService -> jbicService : cleanseOrganizationList(organizationJsonArray)
jbicService -> jbicController : JBICOrganizationEntity[]
activate adminUI #lightgrey
jbicController --> adminUI : [Ok: 200] JBICOrganizationEntity[]
else #pink Failure: token invalid
ARLO --> arloResourcesService: [Error: 401] Unauthorized
deactivate ARLO
arloResourcesService --> jbicService: [Error: 502] Bad gateway
arloResourcesService --> jbicService: [Error: 500] Error in getting organization list
deactivate arloResourcesService
jbicService -> jbicController: [Error] Error in establishing connection with ARLO
jbicController --> adminUI : [Error: 503] Service not available, Error retrieving organization list
adminUI -> admin : show dialog box with error

deactivate ARLO
deactivate jbicService
deactivate jbicController
deactivate adminUI
end

adminUI -> adminUI: Show dropdown with organization list
end

@enduml
