@startuml
actor       Admin             as admin
boundary    adminUI           as adminUI
control     jbicController    as jbicController
collections jbicService      as jbicService
collections arloResourcesService as arloResourcesService
participant ARLO              as ARLO

admin -> adminUI: [Web page] /group/create
admin -> adminUI: [Web view] Select **JBIC** as group type

group Fetch placeholder organizations
activate adminUI #lightgrey
adminUI -> jbicController: [HTTPS GET] /jbic/fetch-arlo-placeholder-organizations
activate jbicController #lightgreen
jbicController -> jbicService: CALL fetchAllOrganizations()

activate jbicService #lightblue


jbicService -> arloResourcesService: getOrganisations()
activate arloResourcesService #teal
arloResourcesService --> ARLO: (Basic auth) CALL /api/<DATE>/auth/resources/organisations/
alt#Gold #ADE792 Success
ARLO -> arloResourcesService : [ok: 200] arloOrganizations: Organizations JSON Array
arloResourcesService -> jbicService : [ok: 200] arloOrganizations: Organizations JSON Array
jbicService -> jbicService : cleanseOrganizationList(organizationJsonArray)
jbicService -> jbicController : JBICOrganizationEntity[]

jbicController --> adminUI : [Ok: 200] JBICOrganizationEntity[]
else #pink Failure: token invalid
ARLO --> arloResourcesService: [Error: 401] Unauthorized
deactivate ARLO
arloResourcesService --> jbicService: [Error: 502] Bad gateway
arloResourcesService --> jbicService: [Error: 500] Error in getting organization list
deactivate arloResourcesService
jbicService -> jbicController: [Error] Error in establishing connection with ARLO
jbicController --> adminUI : [Error: 503] Service not available, Error retrieving organization list
adminUI -> admin : show dialog box with error

deactivate ARLO
deactivate jbicService
deactivate jbicController
deactivate adminUI
end

adminUI -> adminUI: Show dropdown with organization list
end

@enduml
